language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=Postman
    - REQUIRE=""

  matrix:
    - DB=mysql CAKE_VERSION=2.4.10
    - DB=mysql CAKE_VERSION=2.5.5
    - DB=mysql CAKE_VERSION=2.6.7

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1

before_script:
  - curl --silent https://api.github.com/repos/cakephp/cakephp/git/refs/tags
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ./before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false

secure: "TsoeAZwdK27t4D6dImCIqY7viI8hH2EInxHSUCnDt2arw+BFZxU/Cqoxrws6roEAMx67h8MKS6D/bak62TfKzNVYoP3jxU+nSA8sPEJaVZ+UY4iovWqYUK9rDwok84ePIRFiXDIYfa54dT6iwWFUJ3oMlzvGYBGIstse7grUNc4="
